spring:
  server:
    #this shit is not working in the port 9090. I should fix it.
    port: 9090
  datasource:
    url: jdbc:mysql://localhost:3306/rentalCar
    username: root
    password: "rootroot"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop #update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    database-platform: MYSQL
  devtools:
    livereload:
      enabled: true
    add-properties: true
  output:
    ansi:
      enabled: ALWAYS
