spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentalCar?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=False;&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
    username: root
    password: "rootroot"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    database-platform: MYSQL
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    #    prefix: classpath:/templates/
    prefix: file:src/main/resources/templates/
    #    prefix: ${project.basedir}/src/main/resources/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names:
    servlet:
      content-type: text/html
  devtools:
    livereload:
      enabled: true
    add-properties: true
  output:
    ansi:
      enabled: ALWAYS